### ISSUE TITLE
Are you still active?

### ISSUE THREAD

**Issue by olstice** [furtivex/hosts_adultxxx#3]
sorry i didnt mean to sort of ghost you, but i did have another question to ask

**Comment by furtivex** [comment]
Yes 
Hello

**Comment by olstice** [comment]
> Yes Hello

i was wondering if you could try to list down on comment what exactly you did to accomplish the adult site

its just im worried about trying the thing you sent me because well im not educated or skilled at this like you

i want to learn but im scared to try the resources you should me i thought perhaps if you list what you exactly did to accomplish it then 

i would feel more confident to try the resource you gave of the program because now i have a study guide by you

**Comment by furtivex** [comment]
I might make a video on this instead.

**Comment by olstice** [comment]
> I might make a video on this instead.

that would be amazing thank you! will you be sending the link here?

**Comment by olstice** [comment]
> I might make a video on this instead.

like its not that i dont appreicate the resources you sent im just intimidated of not comprehending them without a study guide by you

**Comment by olstice** [comment]
> I might make a video on this instead.

the video link will be here right?

**Comment by furtivex** [comment]
I understand. I'll try to make it easy to understand. And yes, I'll respond to the comment here

**Comment by olstice** [comment]
> I understand. I'll try to make it easy to understand. And yes, I'll respond to the comment here

could you if your willing make two videos one where you try to make it easy to understand and then one where you just explain the instructions but not making it persay easy just talking as if you would to another person who get this


its just i really want to try and see if maybe i can comprehend your video that isnt easy but incase if i cant then theres the easy one

**Comment by olstice** [comment]
> I understand. I'll try to make it easy to understand. And yes, I'll respond to the comment here

Ill message you again the end of next week to see how its going of making the video

is that okay?

**Comment by furtivex** [comment]
Sorry, I've been busy on other projects and preparing for the holidays. I'm curious, do you use my hosts file as well?

I'll get around to it eventually, please be patient with me lol.

**Comment by olstice** [comment]
> Sorry, I've been busy on other projects and preparing for the holidays. I'm curious, do you use my hosts file as well?
> 
> I'll get around to it eventually, please be patient with me lol.

oh yes i do! its been awesome why do you ask?

**Comment by furtivex** [comment]
Well, this is challenging to make a video since it's NSFW content. Can't exactly upload it to youtube. But I'm trying to find a site that is mostly just a search engine. Hang tight I'm working on it

**Comment by furtivex** [comment]
> > Sorry, I've been busy on other projects and preparing for the holidays. I'm curious, do you use my hosts file as well?
> > I'll get around to it eventually, please be patient with me lol.
> 
> oh yes i do! its been awesome why do you ask?

I was just wondering. Hadn't really heard of many people using it. I'm glad you are enjoying it

**Comment by furtivex** [comment]
All done ! https://youtu.be/Fx7xFlI8ya8

**Comment by olstice** [comment]
> All done ! https://youtu.be/Fx7xFlI8ya8

i was also wondering if you had a discord wouldnt mind sending you a friend request?

**Comment by olstice** [comment]
> All done ! https://youtu.be/Fx7xFlI8ya8

so im guessing no on the discord?

**Comment by furtivex** [comment]
I am Furtivex on Discord

**Comment by olstice** [comment]
> Furtivex

sent you a friend request on discord

mine is witheringnature

**Comment by olstice** [comment]
> I am Furtivex on Discord

uh why did you unfriend me? also sorry i havent responded things have been hectic
